Repository FutureMindsTeam/Starklotto, pull requests merged in 2025-03, with the labels that each got.

#63 Fix: Home Page Responsiveness
  packages/nextjs/app/_components/Header.tsx
  packages/nextjs/app/_components/HeroSection.tsx
  packages/nextjs/app/_components/HotDeal.tsx
  packages/nextjs/app/_components/InfiniteCarousel.tsx
  packages/nextjs/app/layout.tsx
  packages/nextjs/app/page.tsx
  packages/nextjs/components/Header.tsx
  packages/nextjs/styles/globals.css
Labels: ODBuild

#70 Main v2
  .github/dependabot.yml
  package.json
  packages/nextjs/app/_components/Header.tsx
  packages/nextjs/app/layout.tsx
  packages/nextjs/app/page.tsx
  packages/nextjs/app/play/confirmation/page.tsx
  packages/nextjs/components/Header.tsx
  packages/nextjs/components/Navbar.tsx
  packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx
  packages/nextjs/components/animated-background.tsx
  packages/nextjs/components/certification-badges.tsx
  packages/nextjs/components/countdown-timer.tsx
  packages/nextjs/components/floating-coins.tsx
  packages/nextjs/components/glowing-button.tsx
  packages/nextjs/components/live-activity-feed.tsx
  packages/nextjs/components/notification.tsx
  packages/nextjs/components/number-selector.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/AddressQRCodeModal.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/GenericModal.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/Wallet.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
  packages/nextjs/components/sections/CTASection.tsx
  packages/nextjs/components/sections/FAQSection.tsx
  packages/nextjs/components/sections/FeaturesSection.tsx
  packages/nextjs/components/sections/HeroSection.tsx
  packages/nextjs/components/sections/HowItWorksSection.tsx
  packages/nextjs/components/sections/index.ts
  packages/nextjs/components/security-badge.tsx
  packages/nextjs/components/security-status.tsx
  packages/nextjs/components/ticket-price-calculator.tsx
  packages/nextjs/components/ui/button.tsx
  packages/nextjs/components/ui/card.tsx
  packages/nextjs/package.json
  packages/nextjs/public/Starklotto.png
  packages/nextjs/tailwind.config.ts
  packages/nextjs/utils/cn.ts
  yarn.lock
Labels: core-dev

#100 feat: add BuyTicketsModal component and integrate into HeroSection
  packages/nextjs/app/buy-tickets/page.tsx
  packages/nextjs/app/page.tsx
  packages/nextjs/components/BuyTicketsModal.tsx
  packages/nextjs/components/sections/HeroSection.tsx
Labels: ODHack12

#102 feat: add admin route and sweepstakes management
  packages/nextjs/.env.example
  packages/nextjs/app/admin/layout.tsx
  packages/nextjs/app/admin/page.tsx
  packages/nextjs/components/StepTracker.tsx
  packages/nextjs/components/scaffold-stark/CustomConnectButton/GenericModal.tsx
  packages/nextjs/components/sweepstakes/ContentDisplay.tsx
  packages/nextjs/components/sweepstakes/FormStep.tsx
  packages/nextjs/components/sweepstakes/ReviewStep.tsx
  packages/nextjs/components/sweepstakes/index.tsx
  packages/nextjs/components/ui/button.tsx
  packages/nextjs/layout/Sidebar.tsx
  packages/nextjs/layout/Topbar.tsx
  packages/nextjs/layout/_data.ts
  packages/nextjs/services/store/sweepstakesStore.ts
  packages/nextjs/styles/globals.css
  packages/nextjs/utils/validations/sweepstakesSchema.ts
Labels: ODHack12

#111 feat: add admin page and Header component
  packages/nextjs/app/admin/page.tsx
  packages/nextjs/components/admin/Header.tsx
Labels: ODHack12, Maintainer - Joseph

#115 Feat/new user panel #106
  packages/nextjs/app/admin/UsersCard.tsx
Labels: ODHack12, Maintainer - Joseph

#114 Implement statistics card
  packages/nextjs/app/admin/page.tsx
  packages/nextjs/app/admin/statisticsCard.tsx
Labels: ODHack12, Maintainer - Joseph
