Repository FutureMindsTeam/Starklotto, pull requests merged in 2025-08, with the labels that each got.

#351 test: enhance event testing in StarkPlayVault contract
  packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
Labels: Manteiner::David

#369 ISSUE-TEST-011: Test contract counters update
  packages/snfoundry/contracts/src/StarkPlayVault.cairo
  packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
Labels: Manteiner::David

#368 Fix: ISSUE-003-CU03
  packages/snfoundry/contracts/tests/test_buy_ticket.cairo
Labels: Maintainer-Jeff

#283 feat: add set/get ticket price functions to Lottery contract
  packages/snfoundry/contracts/src/Lottery.cairo
  packages/snfoundry/contracts/tests/ticket_price_test.cairo
Labels: Internal Contributor

#391 Refactor Lottery Contract: Dynamic Address Implementation
  packages/nextjs/contracts/deployedContracts.ts
  packages/snfoundry/contracts/src/Lottery.cairo
  packages/snfoundry/contracts/tests/test_CU01.cairo
  packages/snfoundry/contracts/tests/test_CU03.cairo
  packages/snfoundry/contracts/tests/test_buy_ticket.cairo
  packages/snfoundry/contracts/tests/test_inventory.md
  packages/snfoundry/contracts/tests/test_jackpot_history.cairo
  packages/snfoundry/scripts-ts/deploy.ts
Labels: Internal Contributor

#401 Buy-ticket-by-quantity
  packages/snfoundry/contracts/src/Lottery.cairo
  packages/snfoundry/contracts/tests/test_CU01.cairo
  packages/snfoundry/contracts/tests/test_CU03.cairo
  packages/snfoundry/contracts/tests/test_buy_ticket.cairo
  packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
  packages/snfoundry/contracts/tests/ticket_price_test.cairo
Labels: Maintainer - Kim

#371 Test `buy_ticket` end to end flow and edge cases
  packages/snfoundry/contracts/Scarb.toml
  packages/snfoundry/contracts/src/Lottery.cairo
  packages/snfoundry/contracts/tests/full_ticket_flow_test.cairo
  packages/snfoundry/contracts/tests/test_CU01.cairo
  packages/snfoundry/contracts/tests/test_erc20.cairo
  packages/snfoundry/contracts/tests/test_jackpot_history.cairo
Labels: Maintainer - Kim

#390 Adding an extensive set of tests for starkplayerc20 burn and mint functionalities
  packages/snfoundry/contracts/tests/test_CU01.cairo
Labels: Manteiner::David

#383 test: tests for on-chain ticket recording and event emission
  packages/snfoundry/contracts/src/Lottery.cairo
  packages/snfoundry/contracts/tests/test_erc20.cairo
  packages/snfoundry/contracts/tests/test_jackpot_history.cairo
  packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
  packages/snfoundry/contracts/tests/test_ticket_recording.cairo
Labels: Maintainer - Kim
